name: Daily Sign

on:
  push:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache/pip
          ${{ github.workspace }}/dist
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', 'main.py', '**/autologin.yml') }}
    - name: do sign
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_REPO: ${{ github.repository }}
        COOKIES: ${{ secrets.BOOKS_COOKIE }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        if [[ -e ${{ github.workspace }}/dist/main ]]; then
          ${{ github.workspace }}/dist/main
        else
          pip install -r requirements.txt
          python main.py
        fi
    - name: Pack as one
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install pyinstaller
        pyinstaller main.py --onefile
